// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtzsavmdnziyyxoebday.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0enNhdm1kbnppeXl4b2ViZGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDQzNjgsImV4cCI6MjA1NzcyMDM2OH0.pCSbpmkWHXOAuQMUYWU42k3xStBMm2IcwZao9GOQqGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);